export const GET_NEWPROJECTS = "GET_NEWPROJECTS";
export const ADD_NEWPROJECTS = "ADD_NEWPROJECTS";
export const ADD_NEWPROJECTSSCREENSHOT = "ADD_PROJECTSSCREENSHOT";
export const UPDATE_NEWPROJECTS = "UPDATE_PROJECTS";
export const REMOVE_NEWPROJECTS = "REMOVE_PROJECTS";